# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: qmra
domain: dev.qmra.org
replicaCount: 1

app_secret_key:
  secret_name: qmra-secret-key-secret
  value: Y21WaGJHeDVYM05sWTNKbGRGOTJZV3gxWlRFSwo=
configmap_name: qmra-configmap

sqlite:
  mount_path: /var/lib/qmra/qmra.db
  hostpath: /var/lib/qmra/qmra.db

static:
  mount_path: /var/cache/qmra/static
  hostpath: /var/cache/qmra/static

image:
  repository: qmra
  tag: local
  pullPolicy: Never
livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /ready
    port: http
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  tlsSecretName: tls-secret-key-ref

tls:
  acme_email: antoine.daurat@kompetenz-wasser.de


podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"




